exports.seed = function (knex) {
  return knex("hospitals")
    .del()
    .then(function () {
      return knex("hospitals").insert([
        {
          id: 1,
          finesse_number: "370000481",
          name: "CHRU de Tours",
          addr1: "2 BD TONNELLE",
          addr2: "",
          town: "Tours",
          dep_code: "37",
          postal_code: "37044",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 2,
          finesse_number: "450000088",
          name: "CHR d'Orléans",
          addr1: "14 AV DE L'HOPITAL",
          addr2: "CS 86709",
          town: "Orléans",
          dep_code: "45",
          postal_code: "45067",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 3,
          finesse_number: "440000289",
          name: "CHU de Nantes",
          addr1: "7 ALL DE L'ILE GLORIETTE",
          addr2: "BP 1005",
          town: "Nantes",
          dep_code: "44",
          postal_code: "44093",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 4,
          finesse_number: "490000031",
          name: "CHU d'Angers",
          addr1: "4 R LARREY",
          addr2: "",
          town: "Angers",
          dep_code: "49",
          postal_code: "49933",
          extra_data: '{"canDoPostMortem": false}',
        },
        {
          id: 5,
          finesse_number: "940110018",
          name: "C.H.I. Créteil",
          addr1: "40 AV DE VERDUN",
          addr2: "",
          town: "Créteil",
          dep_code: "94",
          postal_code: "94010",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 6,
          finesse_number: "590780193",
          name: "CHRU de Lille",
          addr1: "2 AV OSCAR LAMBRET",
          addr2: "",
          town: "Lille",
          dep_code: "59",
          postal_code: "59037",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 7,
          finesse_number: "750100018",
          name: "AP-HP : GH Hôtel-Dieu",
          addr1: "1 PL DU PARVIS DE NOTRE DAME",
          addr2: "",
          town: "Paris",
          dep_code: "75",
          postal_code: "75181",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 8,
          finesse_number: "970100228",
          name: "CHU de Pointe-à-Pitre",
          addr1: null,
          addr2: "BP 465 ",
          town: "Pointe-à-Pitre",
          dep_code: "970",
          postal_code: "97004",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 10,
          finesse_number: "970211207",
          name: "CHU de Martinique",
          addr1: "",
          addr2: "BP 632",
          town: "Fort-de-France",
          dep_code: "972",
          postal_code: "97261",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 13,
          finesse_number: "970408589",
          name: "CHU de la Réunion",
          addr1: "",
          addr2: "BELLEPIERRE",
          town: "Saint-Denis",
          dep_code: "974",
          postal_code: "97400",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 14,
          finesse_number: "350005179",
          name: "CHU de Rennes",
          addr1: "2 R HENRI LE GUILLOUX ",
          addr2: "35000 ",
          town: "Rennes",
          dep_code: "35",
          postal_code: "35000",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 15,
          finesse_number: null,
          name: "CHU de Montpellier",
          addr1: "80 Avenue Augustin Fliche",
          addr2: "",
          town: "Montpellier",
          dep_code: "34",
          postal_code: "34090",
          extra_data: '{"canDoPostMortem": true}',
        },
        {
          id: 11,
          finesse_number: "800000044",
          name: "CHU d'Amiens",
          addr1: "",
          addr2: "",
          town: "Amiens",
          dep_code: "80",
          postal_code: "80054",
          extra_data: '{"canDoPostMortem": false}',
        },
        {
          id: 12,
          finesse_number: "910002773",
          name: "C.H. Sud Francilien",
          addr1: "40 AV SERGE DASSAULT",
          addr2: "",
          town: "Corbeil-Essonnes",
          dep_code: "91",
          postal_code: "91106",
          extra_data: '{"canDoPostMortem": false}',
        },
        {
          id: 16,
          finesse_number: "780800256",
          name: "C.H. Versailles",
          addr1: "177, rue de Versailles",
          addr2: "",
          town: "Versailles",
          dep_code: "78",
          postal_code: "78157",
          extra_data: '{"canDoPostMortem": false}',
        },
        {
          id: 17,
          finesse_number: "770000149",
          name: "C.H. Fontainebleau",
          addr1: "55 Boulevard du Maréchal Joffre",
          addr2: "",
          town: "Fontainebleau",
          dep_code: "77",
          postal_code: "77300",
          extra_data: '{"canDoPostMortem": false}',
        },
        {
          id: 18,
          finesse_number: "130783293",
          name: "Marseille",
          addr1: "264 rue Saint-Pierre",
          addr2: "",
          town: "Marseille",
          dep_code: "13",
          postal_code: "13005",
          extra_data: '{"canDoPostMortem": true}',
        },
      ])
    })
    .then(function () {
      return knex.raw(
        "select pg_catalog.setval(pg_get_serial_sequence('hospitals', 'id'), (select max(id) from hospitals) + 1);"
      )
    })
}
