image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

deployment:
  livenessProbe:
    initialDelaySeconds: 30

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: PORT
      value: "${PORT}"
    - name: NODE_ENV
      value: "production"
    - name: API_URL
      value: "/api"
    - name: POSTGRES_SSL
      value: "true"
    - name: JWT_SECRET
      value: "helloworld"

ingress:
  enabled: true
  # NOTE(douglasduteil): explicitly use HOST during the migration
  # Ensure that we do not override the existing prod
  hosts:
    - host: ${HOST}
      paths:
        - path: /
          servicePort: "${PORT}"
  tls:
    - hosts:
        - ${HOST}
      secretName: ${CI_PROJECT_NAME}-crt
