image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

deployment:
  livenessProbe:
    initialDelaySeconds: 15

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: PORT
      value: "${PORT}"
    - name: NODE_ENV
      value: "production"
    - name: API_URL
      value: "/api"
    - name: POSTGRES_SSL
      value: "true"
    - name: JWT_SECRET
      value: "helloworld"

ingress:
  enabled: true
