export const FRENCH_PUBLIC_HOLIDAY_ENDPOINT = "https://jours-feries-france.antoine-augusti.fr/api/"
export const ACT_DECLARATION_ENDPOINT = "/api/actDeclaration"
export const ACT_LIST_ENDPOINT = "/api/actsList"
export const ACT_DETAIL_ENDPOINT = "/api/actDetail"
export const LOGIN_ENDPOINT = "/api/login"
