version: "3"
services:
  db:
    restart: always
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medle"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      # Master password
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      # API dedicated password
      - POSTGRES_MEDLE_USER=medle
      - POSTGRES_MEDLE_PASSWORD=test
    ports:
      - 5436:5432
    volumes:
      - medle-pgdata:/var/lib/postgresql/data
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.compose
      args:
        - DATABASE_URL=psql://medle:jJFWsfW5ePbN7J@db:5432/medle
        - POSTGRES_SSL=false
        - API_URL=http://localhost:3000/api
        - APP_BASE_URL=http://localhost:3000
        - JWT_SECRET=j63NFc@YNWThqZ
        - MAIL_HOST=localhost
        - MAIL_PORT=25
        - MAIL_USERNAME=
        - MAIL_PASSWORD=
        - MAIL_FROM=Medlé <noreply@sante.gouv.fr>
        - MAIL_CONTACT=contact-medle@sante.gouv.fr
        - LOGIN_DELAY_ATTEMPTS=3
        - LOGIN_DELAY_SECONDS=60
        - AUTHENTICATION_TTL=10800
        - DOCUMENTS_FS_PATH=./documents
    ports:
      - 3000:3000

volumes:
  medle-pgdata:
