version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.compose
      args:
        - DATABASE_URL=${DATABASE_URL}
        - POSTGRES_SSL=${POSTGRES_SSL}
        - API_URL=${API_URL}
        - APP_BASE_URL=${APP_BASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_FROM=${MAIL_FROM}
        - MAIL_CONTACT=${MAIL_CONTACT}
        - LOGIN_DELAY_ATTEMPTS=${LOGIN_DELAY_ATTEMPTS}
        - LOGIN_DELAY_SECONDS=${LOGIN_DELAY_SECONDS}
        - AUTHENTICATION_TTL=${AUTHENTICATION_TTL}
        - DOCUMENTS_FS_PATH=${DOCUMENTS_FS_PATH}
    ports:
      - 80:3000
