version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.compose
      args:
        - DATABASE_URL=${DATABASE_URL}
        - POSTGRES_SSL=${POSTGRES_SSL}
        - API_URL=${API_URL}
        - JWT_SECRET=${JWT_SECRET}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_FROM=${MAIL_FROM}
    ports:
      - 80:3000
