exports.seed = function (knex) {
  return knex("acts")
    .then(function () {
      return knex("acts").insert([
        {
          id: 8348,
          created_at: "2020-05-05 07:00:21.001444",
          updated_at: null,
          deleted_at: null,
          internal_number: "4006413",
          pv_number: "BC/2020/21PSY",
          asker_id: 3860,
          profile: "Victime (vivante)",
          examination_date: "2020-05-05",
          added_by: 9,
          extra_data:
            '{"location": "UMJ", "periodOfDay": "Journée", "personAgeTag": "+ de 18 ans", "personGender": "Féminin", "violenceNatures": ["Coups blessures"], "examinationTypes": ["Somatique"], "violenceContexts": ["Autre type/Autre"]}',
          hospital_id: 4,
        },
        {
          id: 8349,
          created_at: "2020-05-05 07:05:42.458373",
          updated_at: null,
          deleted_at: null,
          internal_number: "20/275",
          pv_number: "2020/19887",
          asker_id: 200,
          profile: "Personne décédée",
          examination_date: "2020-05-04",
          added_by: 2,
          extra_data:
            '{"periodOfDay": "Journée", "examinations": ["Imagerie", "Toxicologie", "Anapath"], "personAgeTag": "+ de 18 ans", "personGender": "Masculin", "examinationTypes": ["Autopsie"]}',
          hospital_id: 1,
        },
        {
          id: 8350,
          created_at: "2020-05-05 07:06:18.911979",
          updated_at: null,
          deleted_at: null,
          internal_number: "20/276",
          pv_number: "70677/1539/2020",
          asker_id: 3860,
          profile: "Personne décédée",
          examination_date: "2020-05-04",
          added_by: 2,
          extra_data:
            '{"periodOfDay": "Journée", "examinations": ["Imagerie", "Toxicologie"], "personAgeTag": "+ de 18 ans", "personGender": "Masculin", "examinationTypes": ["Autopsie"]}',
          hospital_id: 1,
        },
        {
          id: 8351,
          created_at: "2020-05-05 07:07:03.756349",
          updated_at: null,
          deleted_at: null,
          internal_number: "20/277",
          pv_number: "2020/20019",
          asker_id: 200,
          profile: "Personne décédée",
          examination_date: "2020-05-04",
          added_by: 2,
          extra_data:
            '{"periodOfDay": "Journée", "examinations": ["Imagerie"], "personAgeTag": "+ de 18 ans", "personGender": "Masculin", "examinationTypes": ["Examen externe"]}',
          hospital_id: 1,
        },
        {
          id: 8352,
          created_at: "2020-05-05 07:07:30.959806",
          updated_at: null,
          deleted_at: null,
          internal_number: "20/278",
          pv_number: "2020/20063",
          asker_id: 200,
          profile: "Personne décédée",
          examination_date: "2020-05-04",
          added_by: 2,
          extra_data:
            '{"periodOfDay": "Journée", "examinations": ["Imagerie"], "personAgeTag": "+ de 18 ans", "personGender": "Féminin", "examinationTypes": ["Examen externe"]}',
          hospital_id: 1,
        },
        {
          id: 8353,
          created_at: "2020-05-05 07:07:54.163922",
          updated_at: null,
          deleted_at: null,
          internal_number: "20/279",
          pv_number: "2020/8966",
          asker_id: 200,
          profile: "Personne décédée",
          examination_date: "2020-05-04",
          added_by: 4,
          extra_data:
            '{"periodOfDay": "Journée", "examinations": ["Imagerie"], "personAgeTag": "+ de 18 ans", "personGender": "Masculin", "examinationTypes": ["Examen externe"]}',
          hospital_id: 3,
        },
        {
          id: 8354,
          created_at: "2020-05-05 07:18:13.294872",
          updated_at: null,
          deleted_at: null,
          internal_number: "127414-vp",
          pv_number: "2020/6432",
          asker_id: 200,
          profile: "Victime (vivante)",
          examination_date: "2020-05-05",
          added_by: 4,
          extra_data:
            '{"location": "UMJ", "periodOfDay": "Journée", "personAgeTag": "3-17 ans", "personGender": "Féminin", "violenceNatures": ["Coups blessures"], "examinationTypes": ["Psychiatrique"], "violenceContexts": ["Autre type/Scolaire"]}',
          hospital_id: 3,
        },
        {
          id: 8355,
          created_at: "2020-05-05 07:19:09.154954",
          updated_at: null,
          deleted_at: null,
          internal_number: "127418-vc",
          pv_number: "2020/6633",
          asker_id: 200,
          profile: "Victime (vivante)",
          examination_date: "2020-05-05",
          added_by: 4,
          extra_data:
            '{"location": "UMJ", "periodOfDay": "Journée", "personAgeTag": "3-17 ans", "personGender": "Masculin", "violenceNatures": ["Coups blessures"], "examinationTypes": ["Somatique"], "violenceContexts": ["Infra-familiale (hors conjugale)"]}',
          hospital_id: 3,
        },
        {
          id: 8356,
          created_at: "2020-05-05 07:19:42.092872",
          updated_at: null,
          deleted_at: null,
          internal_number: "127417-vc",
          pv_number: "2020/6633",
          asker_id: 3860,
          profile: "Victime (vivante)",
          examination_date: "2020-05-05",
          added_by: 4,
          extra_data:
            '{"location": "UMJ", "periodOfDay": "Journée", "personAgeTag": "+ de 18 ans", "personGender": "Féminin", "violenceNatures": ["Coups blessures"], "examinationTypes": ["Somatique"], "violenceContexts": ["Conjugale"]}',
          hospital_id: 3,
        },
        {
          id: 8357,
          created_at: "2020-05-05 07:30:04.585235",
          updated_at: null,
          deleted_at: null,
          internal_number: "4006416",
          pv_number: "2020/00364",
          asker_id: 200,
          profile: "Victime (vivante)",
          examination_date: "2020-05-05",
          added_by: 4,
          extra_data:
            '{"location": "UMJ", "periodOfDay": "Journée", "personAgeTag": "3-17 ans", "personGender": "Féminin", "violenceNatures": ["Sexuelle"], "examinationTypes": ["Psychiatrique"], "violenceContexts": ["Autre type/Autre"]}',
          hospital_id: 3,
        },
        {
          id: 8358,
          created_at: "2020-05-05 07:31:36.163583",
          updated_at: null,
          deleted_at: null,
          internal_number: "A20058",
          pv_number: "2020/4422",
          asker_id: 200,
          profile: "Gardé.e à vue",
          examination_date: "2020-05-04",
          added_by: 4,
          extra_data:
            '{"location": "Commissariat", "periodOfDay": "Journée", "personAgeTag": "Majeur", "personGender": "Masculin", "examinationTypes": ["Somatique"]}',
          hospital_id: 3,
        },
        {
          id: 8359,
          created_at: "2020-05-05 07:32:53.647037",
          updated_at: null,
          deleted_at: null,
          internal_number: "A200510",
          pv_number: "2020/4335",
          asker_id: 200,
          profile: "Gardé.e à vue",
          examination_date: "2020-05-04",
          added_by: 4,
          extra_data:
            '{"location": "Commissariat", "periodOfDay": "Journée", "personAgeTag": "Majeur", "personGender": "Masculin", "examinationTypes": ["Somatique"]}',
          hospital_id: 3,
        },
        {
          id: 8360,
          created_at: "2020-05-05 07:32:53.647037",
          updated_at: null,
          deleted_at: "2020-05-05 07:32:53.647037",
          internal_number: "A200510",
          pv_number: "2020/4335",
          asker_id: 200,
          profile: "Gardé.e à vue",
          examination_date: "2020-05-04",
          added_by: 9,
          extra_data:
            '{"location": "Commissariat", "periodOfDay": "Journée", "personAgeTag": "Majeur", "personGender": "Masculin", "examinationTypes": ["Somatique"]}',
          hospital_id: 4,
        },
      ])
    })
    .then(function () {
      return knex.raw("select pg_catalog.setval(pg_get_serial_sequence('acts', 'id'), (select max(id) from acts) + 1);")
    })
}
