apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: medle-sealed-secret
  namespace: medle
spec:
  encryptedData:
    SENTRY_TOKEN: >-
      AgCBbmcZFcEPEJhJhr21ddGt2fvs8zZP+gxpbBjE4evn31uM9m2/x6vtBaZhjP5NkcPXXlrVoeXQTbmSO2Ya8qBSvTFLCaC1jhGXgppexGrTSgFzxc3YJpfKRflF52nosriaFkFpCU0/cPkNCkufcIbHgF0nYYmhull1XeF+94LURZ6qH1VETP30AujYPJaWjoJ2Tr6w/EvSTTMXXSkq1EeBWuFymkDPagVntKCDIZyBb6cMNY+erujU+SJRplMavVlRs330rE29ayMBiv0h1ow167SnSrhCyMa6U4SocP8y3h5da1AeALKn98M8Fk/EoILqfHYgNCV4xDzXTqHddXLjSbaFoFeajhvCk1r2PtL60ySAnuOybxYqVmsCQtfabHZcpJJlZ6RJ/Ky0dgMlZZyhoGN5dyRxtQIPzD1FbAwPilhgj3UO+vpLo02vQATM4CYRCT+LlHVglKz6mNDaMsDqHS4fuOi8AyoAudjmUUauropWoow7ewbfYdxE6VlIQSQUL607xu3zes8AICs6mXwDnLw/Ct9YyuEE+hJnsUR+9WWUSxaXYacKCtBU5iqr6dMRYwKXTB2PMJpo8pSwTXuvOSpJUqtEX8OyOwud2qrruZm/W/Yy2hwnH7lukOYVIQLBU0VfCaOBuxTC1B/naxKvGfNVsP5ZOVrR+9OeFkpBQZwH0sm5wD1vwwYBBpTqPOo5AoLs
    JWT_SECRET: >-
      AgDCqtxGT82DGOlEt7fv6MZq3Tt+5UpviETVxv/LGp/3haTo/BQDYlGXRzd1i/hS3ZESFHd7HmgbsjyUmw3MON2k131k7PKgFl5zlX/qixksipyDhlIukos9H02al3jT/lK5+UUK8ARJ97DdT+RfhroVMvNwUCoOlyrGyZA/B60opGOKFBgszvUNqu2phqDnVYdJuM+kj2YvpC/+jf1YD4xvXYdwpaQhLgFFXk7x86GmeFCoza8D5HbstaviUM8FnJ68oWtHMO9y4uQcKoPWAJNngJkjM3mfNrXDGgmKz83QTHV7GYwpM9msi1rU0YQnyuZHAIjuaM2Oe2A1DMA09a8G0hEMHxeGFqrYBdxhNV3ptfGW+tX1CvmCIbVaBALaaTI0M4HWLq9fzK8nwlzJ5qVv97VJ5vHkXbE/rl4lFjl3Hj/sXo3O1WPEJ1bnsqrhvOQwU7fVqsS1b7pwajgOhGfd/S0qd1h3eog70ln2cJzL69Hfivo5393X+iQPu8FueKP59Naz2clWub01lDEiAaHKZUUAlISl4eJiLPCaiVcR5cTX4oxR1tEnSCb2Z9pKFv/3tInxcug///DiXrc/cnYWcYG0ZlR+7Wo9vYdMrMvrfwFHhlwNOWTTSecxuHvZoQHQGoV0mMj8LwjEkdHuEDgpnuI879KO1BiGwljVBdfpdWug64utJSzWdc470txocZrXePKfZ8tgreN3g30SnWQbSGHJ+JNRsLX+XhRWKA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: medle-sealed-secret
    type: Opaque
