apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: medle-sealed-secret
  namespace: medle
spec:
  encryptedData:
    SENTRY_TOKEN: >-
      AgCoQu/Bd3sJpVl6OzXGgSqKRUegXVD1hzxsnhnSlAL8Y2n/yyVG31mZMVqgmcyqNg3/rgfZjkDD8KT2G8XO3PcQySCx0m9LYmTPdP5t0SV8g9q5oeA1ESHuUVj0MYeJbB+K14iKO6le/hvoulnaj7uM+/suKPt1Uj+V9Xf4oFRH9LnRqk9zgS+eUGcF9VAolbj4Yq1ygliZm6MpjheF4A7/+yXZP7lBQIVWlRvIOagdCj+SEv2bxP8Zbj5orvBEGfznbuvNnR7Orllx+x67vYRxK/0KvoWE/i2FByzXLRdmLf6ZEYrHsGmobdsaNCA7L+FyiVick9FCWMuT1idoVzN0Pr7BDycnr1GoNIHmUSlMM/aERFO6Li5Z49KWa0jMVxT0ktuCht6z1EMkKNuygrJZBZWKoICqRaHGMJQ2cJrFPDNLA+1HfVJTlSlpQuFOXztH6xtsmElGMuHNbYd8yw/77jpmR5EbUXAsM40ee0nMMpcoA7s85+9Km8LnwWrvb7ENCREtTwQPxnU2gxnQrVYzMC1gPzGg3RpnNpt6DwKNKu4ZojQEErmUwZ/vHrxCWP/7yIc3II+BwM0JU6gv/GmBfgqasCfmUiVOPLmDsXhFkimFzfRXaXuPx4VJNrHpUIei054mR+awTU9lK8lG2SV146CyoGRqYDfoWX1X2aDozLw6pUwVrjNUPw9kR5HkC0/e4x1K
    JWT_SECRET: >-
      AgCGBctYeWWYhqzJ0lwLJP1gCDKUBa5fYj2W6sSmGnjmhO8C/jgFGhn/eFoqRVGkTrSiQg/+BRIMRogE2aJB18Pga8PAabzA1+3h5DxFh7d7gfGhnj5xyXO1/MjR81a4S5OJIVbfBhdh1oGK7gsfV4806dqnLZILDvyg3BHa1RtdtWopn8ynFhpZvMu6QO+QANLVPeFyVNzUVHnFPm++lA5onM7yZnOhcWGtrR6+ya/o23zxFjzElRYpp10w5r3tzvyBfRx8SDuCsJwzQiv0IP3qTpJjkHe8IwhM7lJ+XzOMfHI1cNJ8NDh9nvNr7hKDfCUodOeU4Q0Uay2ST7imABGQU0qWHo4LJ3g5i/CvNoCsxCYaR+vEjmKwih27oe4V5JnxpTNi0Y77pHt6Ia2fbxTB1VP8d0QVvT0o2U6bPSK9TRJKrsOIKhwu3SjY/D+oxFyRoaKMMKX4He7lyXOXl+nP0mX0yp/WkD6WvSaOAONi7ZQJUUw3CfVF1L4pTW2Zl2FGhhgQZxQ2m66Xntaw8v8U09C6Hx2INkRB8LRrIg9BfzrW8O2LgiQbNaoVm8uHweXhkAUmTzLOhYdAxZKYuHKpy3UQCcTzd1U0uy8N6jcELWJvzWsmystg+ZPKX3Iplndu/iZzu2HHAPv1bmH0mMzBmOQavJ7lBBwJn2WllwHNA+w3w8CKVEtVVD7WCoWnC4AVMf188LjVZ4vPAYUcmw1doiTcvX0oLUtBazz67Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: medle-sealed-secret
    type: Opaque
