apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: medle-sealed-secret
  namespace: medle
spec:
  encryptedData:
    SENTRY_TOKEN: >-
      AgBgspp8mK/TevL0dS7Q2/VvnVbF9lOTe8ckaNkEDX8Ckul4MDFoaLgK5eXbTGjJLSjpFYpU1WlGHxXLAGJWQm6RhmRmd7Qiw3Kc9UpFKD4zslJ+5VcTlz+0GU26cV5RFv2ZthUgGbdB0iO/iwpY1xa1B3NI/7w4/QNYy6bF7+GgnSM3r6j26+LKuVxVCApX1zsPLtitHLhnqei3UzZi5XHMqZ8YecIk9cxb8mGmyAAScCQaRadmwu32rQrQd62fN+IPPLMxHMyNrbWLxzBiilTwO8Qwkq+FTBA5RiFNVd89hnVF+clHxN+3ZQRgrT81sCG+rVJ11Pygop89mfLi682ubXE38lMJJuSyhDkM7D5o1DZWnjQopkof0+BOPthXMgQVzpFZFS/1P1OhcMPWjJN9Mrf6MKSALoJw5QewNosac37F4biP9nWyPQZTeQTzARtfPMzx4hkdKD39bomhkyBFlE3rcXQCGegLvKeW3UhxxViDj7UjzyiRHeSfkkTkjxdO66yu0gSbFG/qhCqj/fh/FIIyXVi3asrpZS4DjEnjm9XwU8jHTP5kmg0RGxyt2qxHG7byBQ0lEfAoxWSDiS6jhaehM9pg4ZohwK4Y4VXcMS55h4TWBOH0Sx1Ng7mNUfaftoGQ4r86S6Qj4ZXasGWOHkW3u9A2gEjvvb6vEll0Vkha6dB5lMBN6BpP1xo8YpP9KCDb
    JWT_SECRET: >-
      AgAEi1F2PkfnuQjH6jlRHwp6KU9cP3LxrLCUgaYKX+q3T/cUANSJ/kPq6tGhAZYHGtvE7AIXonebJk/t/0+baNzLfReoMMPmjWvwhZgpuKTTlbwiENmDBxl1YoCnPD+H6C9t+XfiZjV+6UHhJyCltCtI5xu+KuyCm0rkn4UETyJinXfFc9HQnxbG+2VD7GufMO7vCkSI4cgBnhTkR+fI8cnR/K5sUGcekqTaKUzd00zKqS6/W/9pmS3X+1d756xsPrDYSDwBIVpN3nmV3C8jPlAB6vTdgdhGIaKz8hj2L1IKofqZGuQIPR/fH3tekFfn5VBi0kqAjywau4Dsql3oU7VySeO+e0oVN4TgXws5IbFvyllEYKJQC6ioMoC2qhiz8pw71Go42sEct1R/v2sB8C4gq09tITuJWzp3uT9WJH9gUecJzhkx81JsHZSvd+ZCtTYcU4CYR0otDot34rkNEpa4S3wTm2XTHvJVDnIPiwHaHiPlfU3h63Q09W9utph7iJzprybiuRGbMI/fjwL5jVFaEPL2z3eowevGp7Fakz5UouWjRAlt9nYc/1e7Ex2lyfE0c1MLLDIi43QM5vcAmnzD6lfYjW5GWPZvq/NKZw5AWlXJMNqCAO7PxQstXvuvAJ2WNhekVRtaPSL+VH4jh9WW3pGDUqDyHOSud34cRoY1wbvR1tRZ2QKF3j/2CDT/uQdOrV0OmY20feZzL/qNj7OHpLRnxc5yQlJYyAwnnA==
  template:
    metadata:
      annotations: {}
      name: medle-sealed-secret
    type: Opaque
